name: Release Extension ZIP

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'
      - name: Enable Corepack + pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          pnpm -v
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build extension
        working-directory: apps/extension
        run: pnpm build
      - name: Zip extension
        working-directory: apps/extension
        run: pnpm zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkvocage-extension
          path: apps/extension/checkvocage-extension.zip
