name: Deploy Web to Firebase Hosting

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          pnpm -v
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build web
        working-directory: apps/web
        run: pnpm build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: live
