name: GitHub Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v2.0.0)"
        required: false
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'

      - name: Enable Corepack + pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build extension (all targets incl. options)
        working-directory: apps/extension
        run: pnpm build

      - name: Package extension ZIP
        working-directory: apps/extension
        run: pnpm zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: ${{ github.event.inputs.tag || github.ref_name }}
          generate_release_notes: true
          files: |
            apps/extension/checkvocage-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

